allowBuilds:
  '@google/genai': set this to true or false
  '@mongodb-js/zstd': set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  node-liblzma: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
