#!/usr/bin/env python3
"""
Linux System Hardening Automation

Applies security hardening configurations to Linux systems.

Dependencies:
    No external dependencies (stdlib only)

Usage:
    # Dry run (no changes)
    python harden-linux.py --dry-run

    # Apply hardening
    sudo python harden-linux.py

    # Audit only
    python harden-linux.py --audit
"""

import subprocess
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional
import argparse


class LinuxHardener:
    """Automates Linux system hardening based on CIS benchmarks."""

    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self.changes: List[str] = []
        self.errors: List[str] = []

    def apply_sysctl(self, settings: Dict[str, str]) -> None:
        """Apply kernel parameters via sysctl."""
        sysctl_file = Path("/etc/sysctl.d/99-hardening.conf")

        content = "# Security hardening parameters\n"
        content += "# Generated by harden-linux.py\n\n"

        for key, value in settings.items():
            content += f"{key} = {value}\n"

        if not self.dry_run:
            try:
                sysctl_file.write_text(content)
                subprocess.run(["sysctl", "--system"], check=True, capture_output=True)
                self.changes.append(f"Applied {len(settings)} sysctl settings")
            except Exception as e:
                self.errors.append(f"Failed to apply sysctl: {e}")
        else:
            self.changes.append(f"[DRY RUN] Would apply {len(settings)} sysctl settings")

    def harden_ssh(self) -> None:
        """Apply SSH hardening configuration."""
        ssh_config = """# SSH Hardening Configuration
# Generated by harden-linux.py

# Authentication
PermitRootLogin no
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
MaxAuthTries 3
MaxSessions 2

# Protocol and Encryption
Protocol 2
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Session Security
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
ClientAliveInterval 300
ClientAliveCountMax 2

# Logging
LogLevel VERBOSE
"""
        config_file = Path("/etc/ssh/sshd_config.d/hardening.conf")

        if not self.dry_run:
            try:
                config_file.parent.mkdir(parents=True, exist_ok=True)
                config_file.write_text(ssh_config)

                # Test SSH configuration
                result = subprocess.run(["sshd", "-t"], capture_output=True, text=True)
                if result.returncode == 0:
                    subprocess.run(["systemctl", "reload", "sshd"], check=True)
                    self.changes.append("Applied SSH hardening")
                else:
                    self.errors.append(f"SSH config test failed: {result.stderr}")
            except Exception as e:
                self.errors.append(f"Failed to apply SSH hardening: {e}")
        else:
            self.changes.append("[DRY RUN] Would apply SSH hardening")

    def set_file_permissions(self) -> None:
        """Set secure permissions on critical files."""
        permissions = {
            "/etc/ssh/sshd_config": 0o600,
            "/etc/shadow": 0o600,
            "/etc/gshadow": 0o600,
            "/etc/crontab": 0o600,
            "/etc/cron.d": 0o700,
            "/etc/cron.daily": 0o700,
            "/etc/cron.hourly": 0o700,
            "/etc/cron.monthly": 0o700,
            "/etc/cron.weekly": 0o700,
        }

        for file_path, mode in permissions.items():
            path = Path(file_path)
            if path.exists():
                if not self.dry_run:
                    try:
                        os.chmod(path, mode)
                        os.chown(path, 0, 0)  # root:root
                        self.changes.append(f"Set permissions on {file_path}")
                    except Exception as e:
                        self.errors.append(f"Failed to set permissions on {file_path}: {e}")
                else:
                    self.changes.append(f"[DRY RUN] Would set permissions on {file_path}")

    def disable_services(self, services: List[str]) -> None:
        """Disable unnecessary services."""
        for service in services:
            if not self.dry_run:
                try:
                    result = subprocess.run(
                        ["systemctl", "is-enabled", service],
                        capture_output=True,
                        text=True
                    )
                    if "enabled" in result.stdout:
                        subprocess.run(["systemctl", "disable", service], check=True)
                        subprocess.run(["systemctl", "stop", service], check=True)
                        self.changes.append(f"Disabled service: {service}")
                except Exception as e:
                    # Service may not exist, that's ok
                    pass
            else:
                self.changes.append(f"[DRY RUN] Would disable service: {service}")

    def audit(self) -> Dict[str, bool]:
        """Audit current hardening status."""
        results = {}

        # Check SSH config
        results["ssh_root_login"] = self._check_ssh_setting("PermitRootLogin", "no")
        results["ssh_password_auth"] = self._check_ssh_setting("PasswordAuthentication", "no")

        # Check kernel params
        results["aslr_enabled"] = self._check_sysctl("kernel.randomize_va_space", "2")
        results["ip_forward_disabled"] = self._check_sysctl("net.ipv4.ip_forward", "0")
        results["syn_cookies_enabled"] = self._check_sysctl("net.ipv4.tcp_syncookies", "1")

        # Check file permissions
        results["shadow_permissions"] = self._check_file_permissions("/etc/shadow", 0o600)
        results["sshd_config_permissions"] = self._check_file_permissions("/etc/ssh/sshd_config", 0o600)

        return results

    def _check_sysctl(self, key: str, expected: str) -> bool:
        """Check if sysctl parameter matches expected value."""
        try:
            result = subprocess.run(
                ["sysctl", "-n", key],
                capture_output=True,
                text=True,
                timeout=5
            )
            return result.stdout.strip() == expected
        except Exception:
            return False

    def _check_ssh_setting(self, key: str, expected: str) -> bool:
        """Check if SSH setting matches expected value."""
        try:
            result = subprocess.run(
                ["sshd", "-T"],
                capture_output=True,
                text=True,
                timeout=5
            )
            for line in result.stdout.lower().split("\n"):
                if line.startswith(key.lower()):
                    return expected.lower() in line
            return False
        except Exception:
            return False

    def _check_file_permissions(self, path: str, expected_mode: int) -> bool:
        """Check if file has expected permissions."""
        try:
            file_path = Path(path)
            if not file_path.exists():
                return False
            actual_mode = file_path.stat().st_mode & 0o777
            return actual_mode == expected_mode
        except Exception:
            return False


def main():
    parser = argparse.ArgumentParser(description="Linux System Hardening Automation")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be changed without applying")
    parser.add_argument("--audit", action="store_true", help="Audit current hardening status")
    args = parser.parse_args()

    # Check if running as root (required for most hardening actions)
    if not args.audit and os.geteuid() != 0:
        print("ERROR: This script must be run as root (use sudo)")
        sys.exit(1)

    hardener = LinuxHardener(dry_run=args.dry_run)

    if args.audit:
        print("=== Linux Hardening Audit ===\n")
        results = hardener.audit()

        for check, passed in results.items():
            status = "✓ PASS" if passed else "✗ FAIL"
            print(f"{status}: {check}")

        passed_count = sum(results.values())
        total_count = len(results)
        print(f"\nScore: {passed_count}/{total_count} ({(passed_count/total_count)*100:.1f}%)")
        sys.exit(0 if passed_count == total_count else 1)

    print("=== Linux System Hardening ===\n")

    # Apply kernel hardening
    print("[1/4] Applying kernel parameters...")
    hardener.apply_sysctl({
        "kernel.randomize_va_space": "2",
        "kernel.kptr_restrict": "2",
        "kernel.dmesg_restrict": "1",
        "kernel.yama.ptrace_scope": "2",
        "net.ipv4.ip_forward": "0",
        "net.ipv4.conf.all.accept_redirects": "0",
        "net.ipv4.conf.all.send_redirects": "0",
        "net.ipv4.tcp_syncookies": "1",
        "net.ipv4.conf.all.accept_source_route": "0",
        "net.ipv4.conf.all.rp_filter": "1",
        "fs.protected_hardlinks": "1",
        "fs.protected_symlinks": "1",
        "fs.suid_dumpable": "0",
    })

    # Apply SSH hardening
    print("[2/4] Applying SSH hardening...")
    hardener.harden_ssh()

    # Set file permissions
    print("[3/4] Setting secure file permissions...")
    hardener.set_file_permissions()

    # Disable unnecessary services
    print("[4/4] Disabling unnecessary services...")
    hardener.disable_services([
        "bluetooth.service",
        "cups.service",
        "avahi-daemon.service",
    ])

    print("\n=== Summary ===")
    print(f"\nChanges applied: {len(hardener.changes)}")
    for change in hardener.changes:
        print(f"  ✓ {change}")

    if hardener.errors:
        print(f"\nErrors encountered: {len(hardener.errors)}")
        for error in hardener.errors:
            print(f"  ✗ {error}")
        sys.exit(1)

    print("\n=== Hardening Complete ===")
    print("\nNext steps:")
    print("  1. Review changes in /etc/sysctl.d/99-hardening.conf")
    print("  2. Review SSH config in /etc/ssh/sshd_config.d/hardening.conf")
    print("  3. Run audit: python harden-linux.py --audit")
    print("  4. Reboot to ensure all settings persist")


if __name__ == "__main__":
    main()
